# Generated by Django 5.1.1 on 2024-10-05 17:14

import django.db.models.deletion
import posts.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('is_published', models.CharField(choices=[('Público', 'Público'), ('Arquivado', 'Arquivado')], default='Público', max_length=10, verbose_name='Status')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='Curtidas')),
                ('image', models.ImageField(blank=True, null=True, upload_to=posts.models.Post.post_image_path, verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
