# Generated by Django 5.1.1 on 2024-10-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_url',
            field=models.URLField(default=0, max_length=255),
        ),
    ]
