# Generated by Django 5.1.1 on 2024-10-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_liker_alter_notification_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='liker',
        ),
    ]
